### What is Feature Engineering?
#### Feature Engineering is the process of transforming raw data into meaningful features that improve the performance of machine learning models.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']})
df

   Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

### One Hot Encoding
#### Converts categorial values into binary

In [3]:
# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Color'], dtype=int)

print(df_encoded)

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0
3           1            0          0
4           0            0          1

### Label Encoding
#### Assigns a unique integer to each category and the category should be in order

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.DataFrame({'Size': ['Small', 'Medium', 'Large', 'Medium', 'Small', 'Large']})
df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large

In [6]:
# Initialize Label Encoder
encoder = LabelEncoder()

# Fit and transform
df['Size_encoded'] = encoder.fit_transform(df['Size'])

print(df)

     Size  Size_encoded
0   Small             2
1  Medium             1
2   Large             0
3  Medium             1
4   Small             2
5   Large             0

### Ordinal Encoding
#### Ordinal Encoding assigns integer values to categories that have a natural order (ranking).

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df = pd.DataFrame({'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'Bachelor']})
df

     Education
0  High School
1     Bachelor
2       Master
3          PhD
4     Bachelor

In [9]:
# Define the order
edu_order = [['High School', 'Bachelor', 'Master', 'PhD']]
edu_order

[['High School', 'Bachelor', 'Master', 'PhD']]

In [10]:
# Apply Ordinal Encoding
encoder = OrdinalEncoder(categories=edu_order)
df['Education_encoded'] = encoder.fit_transform(df[['Education']])
print(df)

     Education  Education_encoded
0  High School                0.0
1     Bachelor                1.0
2       Master                2.0
3          PhD                3.0
4     Bachelor                1.0

### Binary Encoding
#### Assign a unique binary code to each category


#### Each category is first converted into an integer (like Label Encoding).
#### Then, that integer is converted into binary digits (0s and 1s).
#### Finally, each binary digit becomes a separate column.

In [11]:
from category_encoders import BinaryEncoder

In [12]:
df = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Yellow', 'Red']})
df

    Color
0     Red
1   Green
2    Blue
3  Yellow
4     Red

In [13]:
# Apply Binary Encoding
encoder = BinaryEncoder(cols=['Color'])
df_encoded = encoder.fit_transform(df)
print(df_encoded)

   Color_0  Color_1  Color_2
0        0        0        1
1        0        1        0
2        0        1        1
3        1        0        0
4        0        0        1

### Target Encoding
#### Target Encoding replaces a categorical value with a number based on the target variable.

In [14]:
from category_encoders import TargetEncoder

In [15]:
df = pd.DataFrame({
    'City': ['Nairobi', 'Nairobi', 'Mombasa', 'Kisumu', 'Mombasa'],
    'Churn': [1, 0, 1, 0, 1]
})
df

      City  Churn
0  Nairobi      1
1  Nairobi      0
2  Mombasa      1
3   Kisumu      0
4  Mombasa      1

In [16]:
# Apply Target Encoding
encoder = TargetEncoder(cols=['City'])
df_encoded = encoder.fit_transform(df['City'], df['Churn'])

df['Encoded_City'] = df_encoded
print(df)

      City  Churn  Encoded_City
0  Nairobi      1      0.585815
1  Nairobi      0      0.585815
2  Mombasa      1      0.656740
3   Kisumu      0      0.521935
4  Mombasa      1      0.656740

### Frequency Encoding
#### Frequency Encoding replaces each category with the frequency (count) of that category in the dataset.
#### Instead of creating multiple columns (like One-Hot), it uses a single column with numeric values.

In [17]:
data = {
    'City': ['Nairobi', 'Nairobi', 'Mombasa', 'Kisumu', 'Mombasa'],
    'Churn': [1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)
df

      City  Churn
0  Nairobi      1
1  Nairobi      0
2  Mombasa      1
3   Kisumu      0
4  Mombasa      1

In [18]:
# Frequency Encoding
freq_map = df['City'].value_counts().to_dict()
df['Encoded_City'] = df['City'].map(freq_map)

print(df)

      City  Churn  Encoded_City
0  Nairobi      1             2
1  Nairobi      0             2
2  Mombasa      1             2
3   Kisumu      0             1
4  Mombasa      1             2